### ISSUE TITLE
The supported JRE versions are 1.5, 1.6, and 1.7

### ISSUE THREAD

**Issue by jagadeeshbabuchinde** [NetAppDocs/snapmanager-oracle#5]
Page: [SnapManager architecture](https://docs.netapp.com/us-en/snapmanager-oracle/unix-installation-cmode/reference_snapmanager_architecture.html)

Is it right information, SMO supports only till JRE 1.7.?

I see the customers running JRE 1.8.0_261

**Comment by ntap-bmegan** [comment]
@netapp-chandaj - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @jagadeeshbabuchinde  - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-pavanrk

**Comment by netapp-pcarriga** [comment]
@jagadeeshbabuchinde Hi Jagadeesh, I can confirm that JRE 1.8 is supported and have updated the documentation to reflect this in the following locations:
[Installation and Setup for UNIX for Data ONTAP Operating in 7-mode > SnapManager for Oracle](https://docs.netapp.com/us-en/snapmanager-oracle/unix-installation-7mode/reference_snapmanager_architecture.html#snapmanager-for-oracle)
[Installation and Setup for UNIX for Clustered Data ONTAP > > SnapManager for Oracle](https://docs.netapp.com/us-en/snapmanager-oracle/unix-installation-cmode/reference_snapmanager_architecture.html#snapmanager-for-oracle)
[Downloading and starting the graphical user interface using Java Web Start](https://docs.netapp.com/us-en/snapmanager-oracle/windows/task_downloading_and_starting_the_graphical_user_interface_using_java_web_start_windows.html?q=Downloading+and+starting+the+graphical+user+interface+using+Java+Web+Start)

Thanks again for your feedback!
